export const data = [
    {
        country: 'France',
        artist: 'Марсель Руссо',
        title: 'Охота Амура',
        material: 'Холст, масло (50х80)',
        price: 14500,
        image: "./img/pic1.jpg",
    },
    {
        country: 'France',
        artist: 'Анри Селин',
        title: 'Дама с собачкой',
        material: 'Акрил, бумага (50х80)',
        price: 16500,
        image: "./img/pic2.jpg",
    },
    {
        country: 'France',
        artist: 'Франсуа Дюпон',
        title: 'Процедура',
        material: 'Цветная литография (40х60) ',
        price: 20000,
        image: "./img/pic3.jpg",
    },
    {
        country: 'France',
        artist: 'Луи Детуш',
        title: 'Роза',
        material: 'Бумага, акрил (50х80) ',
        price: 12000,
        image: "./img/pic4.jpg",
    },
    {
        country: 'France',
        artist: 'Франсуа Дюпон',
        title: 'Птичья трапеза',
        material: 'Цветная литография (40х60) ',
        price: 22500,
        image: "./img/pic5.jpg",
    },
    {
        country: 'France',
        artist: 'Пьер Моранж',
        title: 'Пейзаж с рыбой',
        material: 'Цветная литография (40х60) ',
        price: 20000,
        image: "./img/pic6.jpg",
    }, 
    {
        country: 'England',
        artist: 'Пол Смит',
        title: 'Дикий зверь',
        material: 'Акварель, бумага (50х80)',
        price: 19500,
        image: "./img/englandpic11.jpg",
    },

    {
        country: 'England',
        artist: 'Джон Уайт',
        title: 'Скалистый берег',
        material: 'Цветная литография (40х60)',
        price: 17500,
        image: "./img/englandpic2.jpg",
    },
    {
        country: 'England',
        artist: 'Джим Уотсон',
        title: 'Река и горы',
        material: 'Акварель, бумага (50х80)',
        price: 20500,
        image: "./img/englandpic3.jpg",
    },
    {
        country: 'England',
        artist: 'Юджин Зиллион',
        title: 'Белый попугай',
        material: 'Цветная литография (40х60)',
        price: 15500,
        image: "./img/englandpic4.jpg",
    },
    {
        country: 'England',
        artist: 'Эрик Гиллман',
        title: 'Ночная рыба',
        material: 'Бумага, акрил (50х80)',
        price: 12500,
        image: "./img/englandpic5.jpg",
    },
    {
        country: 'England',
        artist: 'Альфред Барр',
        title: 'Рыжий кот',
        material: 'Цветная литография (40х60)',
        price: 21000,
        image: "./img/englandpic6.jpg",
    },
    {
        country: 'Germany',
        artist: 'Курт Вернер',
        title: 'Над городом',
        material: 'Цветная литография (40х60) ',
        price: 16000,
        image: "./img/germanypic11.jpg",
    },
    {
        country: 'Germany',
        artist: 'Макс Рихтер',
        title: 'Птенцы',
        material: 'Холст, масло (50х80) ',
        price: 14500,
        image: "./img/germanypic2.jpg",
    },
    {
        country: 'Germany',
        artist: 'Мартин Майер',
        title: 'Среди листьев',
        material: 'Цветная литография (40х60) ',
        price: 20000,
        image: "./img/germanypic3.jpg",
    },
    {
        country: 'Germany',
        artist: 'Герман Беккер',
        title: 'Яркая птица',
        material: 'Цветная литография (40х60) ',
        price: 13000,
        image: "./img/germanypic4.jpg",
    },
    {
        country: 'Germany',
        artist: 'Вульф Бауэр',
        title: 'Дятлы',
        material: 'Бумага, акрил (50х80) ',
        price: 20000,
        image: "./img/germanypic5.jpg",
    },
    {
        country: 'Germany',
        artist: 'Вальтер Хартманн',
        title: 'Большие воды',
        material: 'Бумага, акрил (50х80) ',
        price: 23000,
        image: "./img/germanypic6.jpg",
    },
];